// <auto-generated />
using HRTrainingTracker.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRTrainingTracker.Entities.Migrations
{
    [DbContext(typeof(HRTrainingContext))]
    partial class HRTrainingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeTraining", b =>
                {
                    b.Property<int>("TrainingListTrainingID")
                        .HasColumnType("int");

                    b.Property<int>("WithTrainingEmployeeID")
                        .HasColumnType("int");

                    b.HasKey("TrainingListTrainingID", "WithTrainingEmployeeID");

                    b.HasIndex("WithTrainingEmployeeID");

                    b.ToTable("EmployeeTraining");
                });

            modelBuilder.Entity("HRTrainingTracker.Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRTrainingTracker.Entities.Models.Training", b =>
                {
                    b.Property<int>("TrainingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TrainingName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingID");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("EmployeeTraining", b =>
                {
                    b.HasOne("HRTrainingTracker.Entities.Models.Training", null)
                        .WithMany()
                        .HasForeignKey("TrainingListTrainingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRTrainingTracker.Entities.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("WithTrainingEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
